### ISSUE TITLE
坏了，是不是merge错了！？

### ISSUE THREAD

**Issue by onestarshang** [onestarshang/learn_scrapy_in_chinese#2]
不知道是不是搞坏了。。。把分支合并之后，是不是有问题？

**Comment by onestarshang** [comment]
先睡觉去了。。。

**Comment by royxue** [comment]
= =?不知道哎...我去check一下

**Comment by onestarshang** [comment]
好像你change之后，要pull request一下，才能合并到主干。。。【我那个还有一点儿翻完。。。下午搞定好了，但是怎么pullrequest 我不是很清楚啊，反正你要create 一个request才行~

**Comment by royxue** [comment]
我试了一下,create不了= =

**Comment by onestarshang** [comment]
这个问题已经弄清楚了，close。
